# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-09 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('es_cliente', 'Es Cliente'),),
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=8)),
                ('fechaNac', models.DateField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('foto', models.ImageField(upload_to='fotos_empleados')),
                ('fecha_trabajo', models.DateField(auto_now=True)),
                ('dui', models.CharField(max_length=10)),
                ('nit', models.CharField(max_length=17)),
                ('afp', models.CharField(max_length=12)),
                ('isss', models.CharField(max_length=9)),
            ],
            options={
                'permissions': (('view_superuser', 'Vista de SuperUsuario-Administrador'), ('view_seller', 'Vista de Vendedor'), ('view_accounter', 'Vista de Contador')),
            },
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPago', models.CharField(max_length=30)),
                ('fecha_pago', models.DateField()),
                ('salarioBase', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pagoafp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pagoisss', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('insaforp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalHoraExtra', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalSalario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago_planilla', models.DateField()),
                ('nomPlanilla', models.CharField(max_length=30, unique=True)),
                ('totalAFP', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalISSS', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalVacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalInsaforp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalSalarioBase', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalHoras', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costomensual', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalAguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sancion', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_sancion', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Planilla'),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Planilla'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIGPAd.Puesto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
