# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='C001', max_length=10, unique=True),
        ),
    ]
