# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0002_categoria_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
