# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='enviado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='recibido',
            field=models.IntegerField(default=0),
        ),
    ]
