# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0002_auto_20181021_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='enviado',
            field=models.IntegerField(default=1),
        ),
    ]
