# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='puntuacion_total',
            field=models.IntegerField(default=0),
        ),
    ]
