# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
