# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
