# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
