# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180909_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantEntrada', models.IntegerField()),
                ('cantSalida', models.IntegerField()),
                ('cantExistencia', models.IntegerField()),
                ('precEntrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precSalida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precExistencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montoEntrada', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montoSalida', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montoExistencia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
    ]
