# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_reserva_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estadoForo',
            field=models.IntegerField(default=0),
        ),
    ]
