# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-14 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_estadoforo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estadoForo',
            field=models.BooleanField(default=False),
        ),
    ]
