# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('es_cliente', 'Es Cliente'),)},
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_empleados'),
        ),
    ]
