# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='nomPlanilla',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
