# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0003_auto_20180623_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_trabajo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
