# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0004_auto_20180623_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_trabajo',
            field=models.DateField(null=True),
        ),
    ]
