# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-24 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0005_auto_20180623_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPago', models.CharField(max_length=30)),
                ('fecha_pago', models.DateField()),
                ('salarioBase', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagoafp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insaforp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aguinaldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costomensual', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago_planilla', models.DateField()),
                ('nomPlanilla', models.CharField(max_length=30)),
                ('totalSalario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalAFP', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalISSS', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalVacaciones', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalInsaforp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalSalarioBase', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sancion', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=150)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_sancion', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='afp',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dui',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fechaNac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='isss',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nit',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Empleado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Empleado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAd.Planilla'),
        ),
    ]
