# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAd', '0006_auto_20180624_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancion',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
